### ISSUE TITLE
2017年5月

### ISSUE THREAD

**Issue by Chersquwn** [Chersquwn/note#4]
webkit内核的浏览器，当viewport的`initial-scale`不设置为1时，会对字体进行放大渲染。
```css
body, 
body * {
    max-height: 100%;
}
```
可以消除这种现象
